FROM node:latest as build-react
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

#multi stage container
FROM nginx
WORKDIR /usr/share/nginx/html
COPY --from=build-react /app/build/ .
COPY nginx/nginx.conf /etc/nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
