version: "3"
services:
  frontend:
    build:
      context: ./frontend      
    ports: 
               - "3000:80"
  backend:
    ports: 
                - "9090:9090"
    build:
      context: ./backend            
    volumes:
            - backend:/app

volumes:
        backend:
